swagger: '2.0'
type: object
description: Header food, embedded in other objects
properties:
  uid:
    type: string
    required: true
    description: Food unique ID
  name:
    type: string
    required: true
    description: Food name
