swagger: '2.0'
type: object
description: Response object for single video release query
properties:
  videoRelease:
    $ref: '#/definitions/VideoReleaseFull'
    description: Video release, if found
